"""Parallel HAP packaging pool - lane-based TemplatePool with least-loaded queuing.

Background: the original test_screen.py Phase 1 built 100 .ets files sequentially,
and every build_hap did "copy the whole template -> cold build (ohpm install) ->
delete the copy"; the dominant cost was the template copy itself - pure waste,
further serialized by a global file lock.

This module draws on two sources plus one new idea:
  1. TemplatePool from harmony-validate/src/harmony.ts: pre-warmed isolated
     copies, cache reuse, concurrency cap. Those TS semantics are ported to
     Python here (the async variant is hap_pool_async).
  2. ApiPool.AccumulateChoice from ernie-vilg/src/Api.ts: pick an available
     container from the pool or wait - evolved here into "one isolated template
     copy + one worker thread per lane".
  3. New: when every lane is busy, queue on the least-loaded one (least-loaded
     path scheduling) instead of piling all tasks onto the first lane.

Design:
  - Each lane = one isolated template copy (dir/index_ets) + one background
    worker thread + its own queue.
  - Capacity = lane count (default 4) == concurrency cap.
  - Warm-up: the constructor pre-copies `capacity` template copies once
    (keeping oh_modules to skip the first ohpm install).
  - Cache reuse: after each build only entry/build outputs are cleaned while
    oh_modules/.hvigor are kept, so later files on the same lane build
    incrementally and run faster over time.
  - Load balancing: submit() enqueues on the lane with the smallest
    "in-flight + queued" sum.

Usage:
    from hap_pool import HapPool
    pool = HapPool(env, template_dir, capacity=4, copy_caches=True)
    fut = pool.submit(ets_code, bundle_suffix)   # concurrent scheduling
    result = fut.result()                        # {success, hap_path, stdout, stderr}
    # ... after submitting a batch ...
    pool.shutdown()

Thread safety: each lane is only touched by its own thread and no template is
shared, so no global compile lock is needed.
"""

import os
import re
import shutil
import threading
import time
from concurrent.futures import Future
from dataclasses import dataclass, field
from pathlib import Path
from queue import Queue
from typing import List, Optional

from harmony_auto import (
    HarmonyEnv,
    _run,
    _ensure_npm_registry,
    _rmtree_retry,
    extract_errors,
)


# ---------------------------------------------------------------------------
# Template copies (lane working directories)
# ---------------------------------------------------------------------------

def _make_lane_copy(template_src: Path, lane_id: int, copy_caches: bool) -> Path:
    """Copy the template project into an isolated lane copy.

    - Excludes entry/build (regenerated by hvigor)
    - Optionally excludes .hvigor (holds absolute paths; hvigor would treat the
      copy as a migrated project and rebuild everything)
    - copy_caches=True keeps oh_modules, skipping the first ohpm install and
      building incrementally right away
    """
    dst = template_src.parent / f"etssingleui_pool{lane_id}"

    def _ignore(d: str, names: List[str]) -> List[str]:
        p = Path(d)
        skip = {".arkui-x"}
        if not copy_caches:
            skip |= {".hvigor", "oh_modules"}
        if p == template_src / "entry":
            skip.add("build")
        return [n for n in names if n in skip]

    shutil.copytree(template_src, dst, ignore=_ignore)
    return dst


def _clean_build_artifacts(lane_dir: Path) -> None:
    """Clean only entry/build outputs, keeping oh_modules/.hvigor caches (key to warm builds)."""
    entry_build = lane_dir / "entry" / "build"
    if entry_build.exists():
        _rmtree_retry(entry_build)


# ---------------------------------------------------------------------------
# Single build inside a lane (explicit-path version, equivalent to harmony_auto._build_hap_impl without globals)
# ---------------------------------------------------------------------------

def _build_on_lane(
    env: HarmonyEnv,
    lane_dir: Path,
    index_ets: Path,
    ets_code: str,
    bundle_suffix: str = "",
) -> dict:
    if not env.hvigorw or not env.arkuix_sdk:
        return {"success": False, "hap_path": None,
                "stdout": "", "stderr": "hvigorw or ArkUI-X SDK not found"}

    arkuix_sdk_root = Path(env.arkuix_sdk) / "Sdk"
    arkuix_dir = str(arkuix_sdk_root)

    local_props = lane_dir / "local.properties"
    local_props.write_text(f"arkui-x.dir={arkuix_dir.replace(chr(92), '/')}\n")

    _ensure_npm_registry()

    index_ets.parent.mkdir(parents=True, exist_ok=True)
    index_ets.write_text(ets_code, encoding="utf-8")
    os.utime(index_ets, None)
    written = index_ets.read_text(encoding="utf-8")
    first_line = written.strip().split("\n")[0][:80] if written.strip() else "(empty)"
    index_mtime = index_ets.stat().st_mtime
    print(f"[build@lane] Index.ets: {first_line}... ({len(written)} chars) mtime={index_mtime:.0f}")

    # Clear only HAPs left in entry/build from the previous round; never touch
    # the lane-root persist_XXX.hap. Otherwise the next task on the same lane
    # would delete the previous task's persist copy before build_hap_batch moves
    # it away -> shutil.move FileNotFoundError race (guaranteed with 100 files).
    entry_build_dir = lane_dir / "entry" / "build"
    if entry_build_dir.exists():
        for old_hap in entry_build_dir.glob("**/*.hap"):
            old_hap.unlink()

    # ohpm install only on the first round without oh_modules; skip when cached
    if env.ohpm and not (lane_dir / "oh_modules").exists():
        _run([env.ohpm, "install"], cwd=str(lane_dir), timeout=120)

    build_profile = lane_dir / "entry" / "build-profile.json5"
    bp_original = build_profile.read_text(encoding="utf-8")
    bp_text = re.sub(r'\{\s*"name"\s*:\s*"ohosTest"\s*,?\s*\}', '', bp_original)
    bp_text = re.sub(r',\s*,', ',', bp_text)
    bp_text = re.sub(r'\[\s*,', '[', bp_text)
    bp_text = re.sub(r',\s*\]', ']', bp_text)
    build_profile.write_text(bp_text, encoding="utf-8")

    app_json5 = lane_dir / "AppScope" / "app.json5"
    original_text = app_json5.read_text(encoding="utf-8")
    modified = original_text
    custom_bundle = ""
    if bundle_suffix:
        custom_bundle = f"com.test.ui.{bundle_suffix}"
        modified = re.sub(r'"bundleName"\s*:\s*"[^"]*"',
                          f'"bundleName": "{custom_bundle}"', modified)
    modified = re.sub(r'"versionCode"\s*:\s*(\d+)',
                      lambda m: f'"versionCode": {int(m.group(1)) + 1}', modified)
    app_json5.write_text(modified, encoding="utf-8")

    result = None
    try:
        build_env = {
            "DEVECO_SDK_HOME": env.deveco_home or "",
            "ARKUIX_SDK_HOME": arkuix_dir or "",
            "JAVA_HOME": env.java_home or "",
        }
        path_parts = []
        if env.deveco_home:
            path_parts.append(str(Path(env.deveco_home) / "tools" / "node"))
        if env.java_home:
            path_parts.append(str(Path(env.java_home) / "bin"))
        path_parts.append(os.environ.get("PATH", ""))
        build_env["PATH"] = os.pathsep.join(p for p in path_parts if p)

        result = _run(
            [env.hvigorw, "assembleHap", "--no-daemon",
             "-p", "product=default", "-p", "buildMode=debug",
             "--parallel", "--incremental"],
            cwd=str(lane_dir), env_extra=build_env,
        )
        print(f"[build@lane] hvigor exit={result.returncode}")
        if result.returncode != 0:
            err_msg = result.stderr or result.stdout or "(no output)"
            return {"success": False, "hap_path": None,
                    "stdout": result.stdout, "stderr": err_msg}
    finally:
        app_json5.write_text(original_text, encoding="utf-8")
        build_profile.write_text(bp_original, encoding="utf-8")

    deadline = time.time() + 120
    hap_path = None
    while time.time() < deadline:
        hap_candidates = sorted(lane_dir.glob("**/*.hap"),
                                key=lambda p: p.stat().st_mtime, reverse=True)
        if hap_candidates:
            hap_path = str(hap_candidates[0])
            if Path(hap_path).stat().st_mtime >= index_mtime:
                print(f"[build@lane] HAP found: size={Path(hap_path).stat().st_size}")
                break
        time.sleep(1)
    else:
        return {"success": False, "hap_path": None,
                "stdout": result.stdout if result else "",
                "stderr": "BUILD FAILED: No HAP generated within 120s after hvigor build."}

    return {"success": True, "hap_path": hap_path,
            "bundle_name": custom_bundle or "com.example.etssingleui",
            "stdout": result.stdout if result else "",
            "stderr": result.stderr if result else ""}


# ---------------------------------------------------------------------------
# Lane (worker thread + isolated template copy + own queue)
# ---------------------------------------------------------------------------

@dataclass
class _Job:
    code: str
    bundle_suffix: str
    future: Future = field(default_factory=Future)


class _Lane:
    def __init__(self, lane_id: int, env: HarmonyEnv, lane_dir: Path,
                 index_ets: Path):
        self.id = lane_id
        self.env = env
        self.lane_dir = lane_dir
        self.index_ets = index_ets
        self._q: Queue = Queue()
        self._inflight = 0
        self._lock = threading.Lock()
        self._thread = threading.Thread(target=self._run, name=f"hap-lane-{lane_id}",
                                        daemon=True)

    @property
    def load(self) -> int:
        """Load = in-flight + queued (for least-loaded queuing)."""
        with self._lock:
            return self._inflight + self._q.qsize()

    def enqueue(self, job: _Job) -> None:
        self._q.put(job)

    def start(self) -> None:
        self._thread.start()

    def _run(self) -> None:
        while True:
            job = self._q.get()
            if job is None:  # shutdown sentinel
                self._q.task_done()
                break
            with self._lock:
                self._inflight += 1
            try:
                res = _build_on_lane(self.env, self.lane_dir, self.index_ets,
                                     job.code, job.bundle_suffix)
                if res["success"] and res["hap_path"]:
                    # Copy to the lane root (outside entry/build) first;
                    # _clean_build_artifacts only clears entry/build, otherwise
                    # the HAP would be deleted before build_hap_batch moves it away.
                    src = Path(res["hap_path"])
                    stable = self.lane_dir / f"persist_{job.bundle_suffix or '0'}.hap"
                    shutil.copy2(src, stable)
                    res["hap_path"] = str(stable)
                _clean_build_artifacts(self.lane_dir)  # clear outputs, keep caches
                job.future.set_result(res)
            except Exception as e:  # last resort: never let the worker thread die
                job.future.set_result({
                    "success": False, "hap_path": None,
                    "stdout": "", "stderr": f"lane error: {e}",
                })
            finally:
                with self._lock:
                    self._inflight -= 1
                self._q.task_done()


# ---------------------------------------------------------------------------
# HapPool - parallel + warm-up + least-loaded queuing
# ---------------------------------------------------------------------------

class HapPool:
    def __init__(self, env: HarmonyEnv, template_dir: Path, capacity: int = 4,
                 copy_caches: bool = True):
        self.env = env
        self.template_dir = Path(template_dir)
        self.capacity = max(1, int(capacity))
        self.lanes: List[_Lane] = []
        self._template = self.template_dir  # the original is never touched (copies use parent)

        # warm-up: copy `capacity` isolated copies once; afterwards only reuse them
        for i in range(self.capacity):
            lane_dir = _make_lane_copy(self.template_dir, i, copy_caches)
            index_ets = lane_dir / "entry" / "src" / "main" / "ets" / "pages" / "Index.ets"
            lane = _Lane(i, env, lane_dir, index_ets)
            self.lanes.append(lane)
            lane.start()
        print(f"[HapPool] warmed up: {self.capacity} lanes")

    def submit(self, ets_code: str, bundle_suffix: str = "") -> Future:
        """Submit a build job to the least-loaded lane. Returns a Future."""
        job = _Job(code=ets_code, bundle_suffix=bundle_suffix)
        # least-loaded queuing: pick the smallest (in-flight + queued)
        lane = min(self.lanes, key=lambda l: l.load)
        lane.enqueue(job)
        return job.future

    def shutdown(self, timeout: float = None) -> None:
        for lane in self.lanes:
            lane.enqueue(None)  # sentinel to end the thread
        for lane in self.lanes:
            lane._thread.join(timeout)
        # clean up all lane copies afterwards (avoids hundreds of MB piling up)
        for lane in self.lanes:
            if lane.lane_dir.exists():
                _rmtree_retry(lane.lane_dir)


# ---------------------------------------------------------------------------
# Convenience batch API: concurrently package many files into hap_cache / write .FAILED
# ---------------------------------------------------------------------------

def build_hap_batch(
    env: HarmonyEnv,
    ets_files: List[Path],
    hap_dir: Path,
    capacity: int = 4,
    copy_caches: bool = True,
) -> dict:
    """Concurrently build a batch of .ets files; HAPs land in hap_dir, failures write .FAILED.

    Returns {compiled, failed, results} stats.
    """
    template_dir = Path(__file__).resolve().parents[1] / "etssingleui"
    hap_dir = Path(hap_dir)
    hap_dir.mkdir(parents=True, exist_ok=True)

    pool = HapPool(env, template_dir, capacity=capacity, copy_caches=copy_caches)
    futs = {}
    for p in sorted(Path(e) for e in ets_files):
        stem = p.stem
        hap_dest = hap_dir / f"{stem}.hap"
        failed_dest = hap_dir / f"{stem}.FAILED"
        if hap_dest.exists() or failed_dest.exists():
            print(f"{stem} already done. Skip")
            continue
        code = p.read_text(encoding="utf-8")
        futs[p] = (pool.submit(code, stem), hap_dest, failed_dest, stem)

    results = {}
    compiled = 0
    failed = 0
    try:
        for p, (fut, hap_dest, failed_dest, stem) in futs.items():
            build = fut.result()
            results[stem] = build
            if build["success"] and build["hap_path"]:
                shutil.move(build["hap_path"], hap_dest)
                compiled += 1
                print(f"  -> {hap_dest.name}")
            else:
                err = extract_errors(build["stderr"])
                failed_dest.write_text(err, encoding="utf-8")
                failed += 1
                print(f"[BUILD FAIL] {p.name}: {err[:300]}")
    finally:
        pool.shutdown()

    return {"compiled": compiled, "failed": failed, "results": results}


if __name__ == "__main__":
    import sys
    # quick self-test: python hap_pool.py <ets_dir> <hap_dir> [capacity]
    ets_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("./ets")
    hap_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("./hap_cache")
    capacity = int(sys.argv[3]) if len(sys.argv) > 3 else 4
    from harmony_auto import detect_env
    env = detect_env()
    print(env.summary())
    stat = build_hap_batch(env, list(ets_dir.glob("*.ets")), hap_dir, capacity=capacity)
    print(f"\n[Done] compiled={stat['compiled']} failed={stat['failed']}")
